### ISSUE TITLE
Problem reproducing the example images

### ISSUE THREAD

**Issue by abdo-eldesokey-kaust** [vpulab/ovam#2]
Hi,
Thank you for releasing the code in this nice and clean form!
I am having two issues:
- The seed specified in the notebook "123456" does not produce the intended images for the monkey and the cat!
- The optimization takes around 5 minutes on an A100 unlike what is mentioned in the paper (1 minute). 
Best regards,

**Comment by pablomm** [comment]
Hi! Thank you for your questions, and apologies for the delayed response—I wasn’t receiving notifications for activity in the repository. Although some time has passed, here are responses in case they’re still relevant:

- Seed for Image Generation:
This issue could be due to differences in torch or diffusers versions and the use of xformers. I’ve seen similar discrepancies across versions and systems. The monkey and cat examples were likely run on my MacOS setup with an MPS backend and torch==2.1.0. The rest of the work was done using CUDA, which may have led to differences in generated outputs.

- Computation Time:
The discrepancy in optimization time might relate to differences in the number of epochs used in the example versus what was specified in the main work. There’s a link in the README to the script with the precise parameters we used to perform the optimization in near 1 minute (learning rate / number of epochs). Additionally, other factors like network throughput might affect runtime, even on a faster GPU.

I’ll close this issue due to the time passed, but please feel free to reopen it if needed.

**Comment by jhan-lee** [comment]
![image](https://github.com/user-attachments/assets/eb1904a6-8fd5-4bbe-ae53-2a30cc17f73f)

![image](https://github.com/user-attachments/assets/d789c2b5-27b6-476c-8e46-6ddebffe8701)

Seed 123456, I have the same issue. I wanted to ask about this problem but, it was already opened. :) My torch version is 2.1.0 at Ubuntu 22.04. My result was similar. Thanks to your answer, I think it's not a big deal. Have a nice day.
